language: python
python:
  - "2.6"
  - "2.7"
services:
  - riak
install: 
  - "pip install -r requirements.pip --use-mirrors"
  - "python setup.py install"
script: trial riakasaurus
notifications:
  email:
    - colin.alston@gmail.com

